version: "3.9"

services:
  next-app:
    container_name: portfolio
    platform: linux/amd64
    image: rivernguyen1309/portfolio:latest

    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_URL: ${APP_URL}

    restart: always

    ports:
      - "127.0.0.1:3001:3000"

    env_file:
      - .env

    environment:
      VISITORS_DATA_PATH: /app/data/visitors.json

    volumes:
      - app-data:/app/data

    networks:
      - portfolio

networks:
  portfolio:
    external: true

volumes:
  app-data:
